src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cet email est déjà utilisé")
 */
class Client implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

     /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Merci d'entrer votre prenom!")
     */

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Merci d'entrer votre prenom!")
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Merci d'entrer votre nom!")
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, options={"unique":true})
     * @Assert\NotBlank(message="Merci d'entrer votre Email!")
     * @Assert\Email(message="Merci d'entrer un Email valide!")
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity=Figures::class, mappedBy="id_client", orphanRemoval=true)
     */
    private $figures;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="client", orphanRemoval=true)
     */
    private $commentaires;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $activation_token;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reset_token;


    /**
     * Client constructor.
     */
    public function __construct()
    {
        $this->figures = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    /**
     * @param string $first_name
     * @return $this
     */
    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    /**
     * @param string $last_name
     * @return $this
     */
    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getUsername(): ?string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @param string $password
     * @return $this
     */
    public function setPassword(string $password): self
    {
        $this->password =  $password;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     * @return $this
     */
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getRoles()
    {
        return array('ROLE_USER');
    }

    /**
     *
     */
    public function eraseCredentials()
    {
    }

    /**
     * @return string|null
     */
    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    /**
     * @return Collection|Figures[]
     */
    public function getFigures(): Collection
    {
        return $this->figures;
    }

    /**
     * @param Figures $figure
     * @return $this
     */
    public function addFigure(Figures $figure): self
    {
        if (!$this->figures->contains($figure)) {
            $this->figures[] = $figure;
            $figure->setIdClient($this);
        }

        return $this;
    }

    /**
     * @param Figures $figure
     * @return $this
     */
    public function removeFigure(Figures $figure): self
    {
        if ($this->figures->contains($figure)) {
            $this->figures->removeElement($figure);
            // set the owning side to null (unless already changed)
            if ($figure->getIdClient() === $this) {
                $figure->setIdClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    /**
     * @param Commentaire $commentaire
     * @return $this
     */
    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setClient($this);
        }

        return $this;
    }

    /**
     * @param Commentaire $commentaire
     * @return $this
     */
    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getClient() === $this) {
                $commentaire->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    /**
     * @param string|null $activation_token
     * @return $this
     */
    public function setActivationToken(?string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * @param string|null $image
     * @return $this
     */
    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    /**
     * @param string|null $reset_token
     * @return $this
     */
    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }
}

src/Entity/Figures.php
<?php

namespace App\Entity;

use App\Repository\FiguresRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping\JoinColumn;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=FiguresRepository::class)
 */
class Figures
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Merci d'entrer un nom de figure!")
     */
    private $figure;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Merci d'entrer une description!")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Merci d'entrer un groupe de figure!")
     */
    private $groupe;

    /**
     * @ORM\Column(type="integer", options={"default":0})
     */
    private $featured_image = 0;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="id_figure", orphanRemoval=true, cascade={"persist"})
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=Video::class, mappedBy="id_figure", orphanRemoval=true, cascade={"persist"})
     */
    private $videos;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="figures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_client;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="figure", orphanRemoval=true)
     */
    private $commentaires;

    /**
     *
     */
    CONST GROUP = [
        'Groupe 1',
        'Groupe 2',
    ];

    /**
     * Figures constructor.
     */
    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getFigure(): ?string
    {
        return $this->figure;
    }

    /**
     * @param string $figure
     * @return $this
     */
    public function setFigure(string $figure): self
    {
        $this->figure = $figure;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return $this
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getGroupe(): ?int
    {
        return $this->groupe;
    }

    /**
     * @param int $groupe
     * @return $this
     */
    public function setGroupe(int $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getFeaturedImage(): ?int
    {
        return $this->featured_image;
    }

    /**
     * @param int $featured_image
     * @return $this
     */
    public function setFeaturedImage(int $featured_image): self
    {
        $this->featured_image = $featured_image;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getGroupeText(): ?string
    {
        return self::GROUP[$this->groupe];
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    /**
     * @param Image $image
     * @return $this
     */
    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setIdFigure($this);
        }

        return $this;
    }

    /**
     * @param Image $image
     * @return $this
     */
    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getIdFigure() === $this) {
                $image->setIdFigure(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    /**
     * @param Video $video
     * @return $this
     */
    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setIdFigure($this);
        }

        return $this;
    }

    /**
     * @param Video $video
     * @return $this
     */
    public function removeVideo(Video $video): self
    {
        if ($this->videos->contains($video)) {
            $this->videos->removeElement($video);
            // set the owning side to null (unless already changed)
            if ($video->getIdFigure() === $this) {
                $video->setIdFigure(null);
            }
        }

        return $this;
    }

    /**
     * @return client|null
     */
    public function getIdClient(): ?client
    {
        return $this->id_client;
    }

    /**
     * @param client|null $id_client
     * @return $this
     */
    public function setIdClient(?client $id_client): self
    {
        $this->id_client = $id_client;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    /**
     * @param \DateTimeInterface $created_at
     * @return $this
     */
    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    /**
     * @param \DateTimeInterface $updated_at
     * @return $this
     */
    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @throws \Exception
     */
    public function updateTimestamps()
    {
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt( new \DateTime(null, new \DateTimeZone('Europe/Paris')) );
        }
            $this->setUpdatedAt( new \DateTime(null, new \DateTimeZone('Europe/Paris')) );
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    /**
     * @param Commentaire $commentaire
     * @return $this
     */
    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setFigure($this);
        }

        return $this;
    }

    /**
     * @param Commentaire $commentaire
     * @return $this
     */
    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getFigure() === $this) {
                $commentaire->setFigure(null);
            }
        }

        return $this;
    }
}

src/Form/FigureType.php
<?php

namespace App\Form;

use App\Entity\Figures;
use App\Form\ImageType;
use App\Form\VideoType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class FigureType
 * @package App\Form
 */
class FigureType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('figure', null, [
                'empty_data' => ''
            ])
            ->add('description', null, [
                'empty_data' => ''
            ])
            ->add('groupe', ChoiceType::class,[
                'choices' => $this->getGroup(),
                'empty_data' => 0
            ])
            ->add('images', ImageType::class, [
                'mapped' => false,
                'required' => false,
                'label' => 'Images : ',
            ])
            ->add('videos', VideoType::class, [
                'mapped' => false,
                'required' => false,
                'label' => 'Vidéos : '
            ])
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Figures::class,
        ]);
    }

    /**
     * @return array
     */
    private function getGroup()
    {
        $group = Figures::GROUP;
        $output = [];

        foreach ($group as $key => $value){
            $output[$value] = $key;
        }

        return $output;
    }
}

templates/pages/figures/create.html.twig
{% extends 'base.html.twig' %}
{% block title %}Création de figure{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <script src="{{ asset('js/figure.js') }}"></script>
{% endblock %}
{% block body %}
    <div class="jumbotron text-center mt-5-responsive">
        <h1> Création de figure</h1>
    </div>
    {{ parent() }}
    <div class="container mt-2 mb-4-responsive">
        {{ form_start(form) }}
        {{ form_row(form.figure) }}
        {{ form_row(form.description) }}
        {{ form_row(form.groupe) }}
        {{ form_row(form.images) }}
        <div class="video">
            {{ form_row(form.videos) }}
            <div class="text-center">
                <legend class="col-form-label">Ajouter des vidéos : <img src="{{ asset("uploads") }}/plus.png" class="plus"></legend>
            </div>
        </div>
        
        <div class="text-right">
            <input type="submit" class="btn btn-primary" formnovalidate="" value="Créer une nouvelle figure">
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/pages/figures/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ figure.figure }}{% endblock %}
{% block body %}
{% block stylesheets %}
    {{ parent() }}
    <script src="{{ asset('js/show.js') }}"></script>
    <script src="{{ asset('js/loadMore.js') }}"></script>
{% endblock %}
<div class='mt-6'></div>
{{ parent() }}
<div class="container mt-5 mb-4-responsive">
    <div class="row justify-content-center">          
        <div class="col-md-10 col-md-offset-1 mb-4"> 
            <div class="card">
                <img class="card-img-top" src="
                {% if figure.images.0.image is defined %}
                    {{ asset('uploads') ~ "/" ~ figure.images.0.image }}
                {% else %}
                    {{ asset('uploads') ~ "/default.jpg" }}
                {% endif %}
                ">
                <div class="card-body">
                    <h4 class="card-title"><strong> {{ figure.figure }}</strong></h4>
                    
                    <hr>
                    <ul class="list-inline trick-data text-center">
                        <li class="list-inline-item">
                            Par : {{ figure.IdClient.Username }}
                        </li> |
                        <li class="list-inline-item">
                            Ajouté le {{ figure.createdAt|date('d-m-Y H:i') }} (<small>Mise à jour le :  {{ figure.updatedAt|date('d-m-Y H:i') }} </small>)
                        </li>|
                        <li class="list-inline-item">
                            Catégorie : {{ figure.GroupeText }}
                        </li>
                    </ul>
                    <hr>
                    
                    <!-- Start Carousel -->
                    <div class="row show-responsive">
                        {% if figure.images is not empty %}

                            <div class="
                                {% if figure.videos is empty %}
                                    col-xl-12 
                                {% else %}
                                    col-xl-6
                                {% endif %}
                            mb-figure-show">
                                <div class='h-100 image-border'>
                                    <div id="carouselExampleControls1" class="carousel slide h-100" >
                                        <div class="carousel-inner h-100">
                                            {% for image in figure.images %}
                                                <div class="carousel-item h-100 {% if flag_image is not defined %}active{% endif %}">
                                                    <embed class='d-block w-100 image-height border-radius-solid' src="{{ asset('uploads') ~ "/" ~ image.image }}" frameborder="0" allow="autoplay; encrypted-media"  allowfullscreen />
                                                </div>
                                                {% set flag_image = true %}
                                            {% endfor %}
                                        </div>
                                        {% if figure.images|length > 1 %}
                                            <a class="carousel-control-prev" href="#carouselExampleControls1" role="button" data-slide="prev">
                                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                                <span class="sr-only">Previous</span>
                                            </a>
                                            <a class="carousel-control-next" href="#carouselExampleControls1" role="button" data-slide="next">
                                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                                <span class="sr-only">Next</span>
                                            </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                        <div class=
                        {% if figure.images is empty %}
                        "col-xl-12"
                        {% else %}
                        "col-xl-6"
                        {% endif %}
                        >
                        {% if figure.videos is not empty %}
                            <div class='h-100 card-img-top'>
                                <div id="carouselExampleControls" class="carousel slide h-100" >
                                    <div class="carousel-inner h-100">
                                        {% for video in figure.videos %}
                                            <div class="carousel-item h-100 {% if flag_video is not defined %}active{% endif %}">
                                                <embed class='d-block w-100 border-radius-solid image-height' src="{{ video.video }}" frameborder="0" allow="autoplay; encrypted-media"  allowfullscreen />
                                            </div>
                                            {% set flag_video = true %}
                                        {% endfor %}
                                    </div>
                                    {% if figure.videos|length > 1 %}
                                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                        </div>
                    </div>
                    {% if figure.images is not empty or figure.videos is not empty %}
                        <div class="text-center">
                            <input type='submit' class="btn btn-info show-image" value='Afficher le contenu'>
                            <input type='submit' class="btn btn-info hide-image" value='Cacher le contenu'>
                        </div>
                    {% endif %}
                    <!-- End Carousel -->
                    {% if app.user %}
                        <hr />
                        <div class='d-flex'>
                            <div class="ml-auto ml-responsive">
                                <a href="{{ path('figure.edit', {'id': figure.id}) }}" class="btn btn-outline-info btn-sm btn-trick mr-2">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </div>
                            <form action="{{ path('figure.delete', {'id': figure.id}) }}" method='POST' onsubmit="return confirm('Supprimer la figures ?')">
                                <input type="hidden" name="_method" value="delete">
                                <button class="btn btn-outline-danger btn-sm btn-trick">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </button>
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ figure.id) }}">
                            </form>
                        </div>
                    {% endif %}
                    <hr />
                    <h5 class="card-title">Description</h5>
                    <p class="card-text text-justify text-break">{{ figure.description }}</p>
                    <p>
                        {% if app.user %}
                        <hr />
                        {{ form_start(form) }}
                            {{ form_row(form.commentaire) }}
                            <div class="text-right">
                                <input type="submit" class="btn btn-primary" value="Ajouter" formnovalidate="">
                            </div>
                        {{ form_end(form) }}
                        {% endif %}
                        <hr />
                        {% if figure.commentaires is not empty %}
                            <h5 class="card-title">Commentaire ({{ figure.commentaires|length }})</h5>
                            {%  set hide = '' %}
                            {% for commentaire in figure.commentaires %}
                                {% set counter = ( counter | default(0) ) + 1 %}
                                {% if counter > 10 %}
                                    {% set hide = " hide " %}
                                {% endif %}
                                <table class='{{ hide }}'>
                                    <tr>
                                        <td>
                                            {% if commentaire.client.image %}
                                            <img src="{{ asset('uploads') }}/{{ commentaire.client.image }}" class='images_round mr-1'> 
                                            {% else %}
                                            <img src="{{ asset('uploads') }}/default_profil.jpg" class='images_round mr-1'> 
                                            {% endif %}
                                        </td>
                                        <td class='w-100'>
                                            <div class='card p-3 m-3'>
                                                <span class='mb-2'>
                                                    {{ commentaire.client.username|raw }}, le : {{ commentaire.createdAt|date('d-m-Y H:i') }}
                                                </span>
                                                {{ commentaire.commentaire|raw }}
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            {% endfor %}
                        {% else %}
                            <h5 class="card-title">Pas de commentaire</h5>
                        {% endif %}
                        {% if figure.commentaires|length > 10 %}
                            <div class='text-center'>   
                                <a href='#' id='loadMore'>
                                    <i class="fa fa-plus-circle fa-3" aria-hidden="true"></i>
                                </a>
                            </div>
                        {% endif %}
                    </p>
                </div>
            </div>
            <!--  End Trick -->
        </div>
    </div>
</div>
{% endblock %}